name: Changed Files

on:
  workflow_call:
    outputs:
      all:
        description: "All changed files"
        value: ${{ jobs.changed_files.outputs.all }}
      puppet:
        description: "All changed Puppet files"
        value: ${{ jobs.changed_files.outputs.puppet }}
      ruby:
        description: "All changed Ruby files"
        value: ${{ jobs.changed_files.outputs.ruby }}
      other:
        description: "All changed files that are not Puppet or Ruby"
        value: ${{ jobs.changed_files.outputs.other }}
      benchmarks:
        description: "All changed benchmark files"
        value: ${{ jobs.changed_files.outputs.benchmarks }}
      facts:
        description: "All changed fact files"
        value: ${{ jobs.changed_files.outputs.facts }}
      features:
        description: "All changed feature files"
        value: ${{ jobs.changed_files.outputs.features }}
      hiera:
        description: "All changed hiera files"
        value: ${{ jobs.changed_files.outputs.hiera }}
      plans:
        description: "All changed plan files"
        value: ${{ jobs.changed_files.outputs.plans }}
      providers:
        description: "All changed provider files"
        value: ${{ jobs.changed_files.outputs.providers }}
      puppet_x:
        description: "All changed puppet_x files"
        value: ${{ jobs.changed_files.outputs.puppet_x }}
      tasks:
        description: "All changed task files"
        value: ${{ jobs.changed_files.outputs.tasks }}
      tests_acceptance:
        description: "All changed acceptance test files"
        value: ${{ jobs.changed_files.outputs.tests_acceptance }}
      tests_data:
        description: "All changed data test files"
        value: ${{ jobs.changed_files.outputs.tests_data }}
      tests_unit:
        description: "All changed unit test files"
        value: ${{ jobs.changed_files.outputs.tests_unit }}
      types:
        description: "All changed type files"
        value: ${{ jobs.changed_files.outputs.types }}
      utils:
        description: "All changed util files"
        value: ${{ jobs.changed_files.outputs.utils }}
      workflows:
        description: "All changed workflow files"
        value: ${{ jobs.changed_files.outputs.workflows }}

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      all: "${{ steps.changed-files-yaml.outputs.all_all_changed_and_modified_files_count }}"
      puppet: "${{ steps.changed-files-yaml.outputs.puppet_all_changed_and_modified_files_count }}"
      ruby: "${{ steps.changed-files-yaml.outputs.ruby_all_changed_and_modified_files_count }}"
      other: "${{ steps.changed-files-yaml.outputs.other_all_changed_and_modified_files_count }}"
      benchmarks: "${{ steps.changed-files-yaml.outputs.benchmarks_all_changed_and_modified_files_count }}"
      facts: "${{ steps.changed-files-yaml.outputs.facts_all_changed_and_modified_files_count }}"
      features: "${{ steps.changed-files-yaml.outputs.features_all_changed_and_modified_files_count }}"
      hiera: "${{ steps.changed-files-yaml.outputs.hiera_all_changed_and_modified_files_count }}"
      plans: "${{ steps.changed-files-yaml.outputs.plans_all_changed_and_modified_files_count }}"
      providers: "${{ steps.changed-files-yaml.outputs.providers_all_changed_and_modified_files_count }}"
      puppet_x: "${{ steps.changed-files-yaml.outputs.puppet_x_all_changed_and_modified_files_count }}"
      tasks: "${{ steps.changed-files-yaml.outputs.tasks_all_changed_and_modified_files_count }}"
      tests_acceptance: "${{ steps.changed-files-yaml.outputs.tests_acceptance_all_changed_and_modified_files_count }}"
      tests_data: "${{ steps.changed-files-yaml.outputs.tests_data_all_changed_and_modified_files_count }}"
      tests_unit: "${{ steps.changed-files-yaml.outputs.tests_unit_all_changed_and_modified_files_count }}"
      types: "${{ steps.changed-files-yaml.outputs.types_all_changed_and_modified_files_count }}"
      utils: "${{ steps.changed-files-yaml.outputs.utils_all_changed_and_modified_files_count }}"
      workflows: "${{ steps.changed-files-yaml.outputs.workflows_all_changed_and_modified_files }}"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Get all changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml_from_source_file: .github/changed_files.yml